data_dir: "F:/Data/selfi2anime"
output_dir: "output"
use_gpu: true
phase: "train"
light: true

lr: 0.0001
weight_decay: 0.0001
batch_size: 1
iterations: 1000000
decay_step: 500000
sample_freq: 4000
snap_freq: 2000
save_freq: 100000
log_freq: 10

gan_mode: "lsgan"
lambda_adv: 1
lambda_cyc: 10
lambda_idt: 10
lambda_cam: 1000

base_width: 64
n_res: 4
n_dis: 6
img_size: 256
img_ch: 3

# base_width: 16
# n_res: 1
# n_dis: 6
# img_size: 128
